name: Azure Static Web Apps CI/CD (app subdomain)

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy_app_subdomain:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job (app)
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy to app subdomain
        id: builddeploy_app_subdomain
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Use the same Static Web Apps token so this deploy targets the same property
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_COAST_0D53A9710 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          app_location: "/svelte-app" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######


