name: Azure Static Web Apps CI/CD (Unified)

on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'pnpm'
          cache-dependency-path: 'svelte-app/pnpm-lock.yaml'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '10.14.0'

      - name: Install dependencies
        run: |
          cd svelte-app
          pnpm install --frozen-lockfile

      - name: Build application
        run: |
          cd svelte-app
          pnpm run build

      # Deploy to production environment (main Azure Static Web App)
      - name: Deploy to Production
        id: deploy_prod
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_COAST_0D53A9710 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/svelte-app"
          api_location: "api"
          output_location: "build"
          production_branch: "master"

      # Deploy to dev environment (staging slot)
      - name: Deploy to Development
        id: deploy_dev
        if: github.event_name == 'pull_request' || (github.ref == 'refs/heads/master' && github.event_name == 'push')
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_COAST_0D53A9710 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/svelte-app"
          api_location: "api"
          output_location: "build"
          deployment_environment: "dev"

      # Configure custom domains and SSL certificates
      - name: Configure Custom Domains and SSL
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: azure/CLI@v1
        env:
          AZURE_STATIC_WEBAPP_NAME: ${{ secrets.AZURE_STATIC_WEBAPP_NAME }}
          AZURE_RG: ${{ secrets.AZURE_RG }}
        with:
          azcliversion: 'latest'
          inlineScript: |
            # Configure custom domains if secrets are available
            if [ -z "$AZURE_STATIC_WEBAPP_NAME" ] || [ -z "$AZURE_RG" ]; then
              echo "AZURE_STATIC_WEBAPP_NAME or AZURE_RG not set; skipping custom domain configuration"
              echo "Note: Azure Static Web Apps automatically provides SSL certificates for *.azurestaticapps.net domains"
            else
              echo "Configuring custom domains for Static Web App: $AZURE_STATIC_WEBAPP_NAME"
              
              # The main domain (production)
              echo "Setting up production domain: polite-coast-0d53a9710.1.azurestaticapps.net"
              
              # The dev subdomain - Azure SWA automatically handles SSL for subdomains
              echo "Setting up dev subdomain: dev.polite-coast-0d53a9710.1.azurestaticapps.net"
              echo "SSL certificate will be automatically provisioned by Azure Static Web Apps"
              
              # If you need custom domain configuration, uncomment and modify:
              # az staticwebapp hostname set --name "$AZURE_STATIC_WEBAPP_NAME" --resource-group "$AZURE_RG" --hostname "polite-coast-0d53a9710.1.azurestaticapps.net"
              # az staticwebapp hostname set --name "$AZURE_STATIC_WEBAPP_NAME" --resource-group "$AZURE_RG" --hostname "dev.polite-coast-0d53a9710.1.azurestaticapps.net"
            fi

      # Display deployment URLs
      - name: Display Deployment Information
        if: always()
        run: |
          echo "🚀 Deployment Summary:"
          echo "Production URL: https://polite-coast-0d53a9710.1.azurestaticapps.net"
          echo "Development URL: https://dev.polite-coast-0d53a9710.1.azurestaticapps.net"
          echo ""
          echo "🔒 SSL Certificate Information:"
          echo "Both URLs are secured with SSL certificates automatically provided by Azure Static Web Apps"
          echo "No browser warnings should occur as Azure manages the certificates for *.azurestaticapps.net domains"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_COAST_0D53A9710 }}
          action: "close"
          app_location: "/svelte-app"
          api_location: "api"
          output_location: "build"
